### PR TITLE
WIP: Camera Stream

### LINKED ISSUE #55: Refactor camera code

### PR DESCRIPTION
**Pull request by SoupeDeKiwis**
This PR aims to give access to the stream of the front camera.

### CODE REVIEW

**Review by dobios — APPROVED** [review]

**Comment by SoupeDeKiwis** [comment]
Please do not merge this branch until I refactored the code.

**Comment by samuelchassot** [comment]
I can't run Gradle on my machine, do you have only java 8 installed? @AndreaClement

**Comment by SoupeDeKiwis** [comment]
> I can't run Gradle on my machine, do you have only java 8 installed? @AndreaClement

Strange, Android Studio only sees Java 8. I will correct that.

**Comment by samuelchassot** [comment]
> > I can't run Gradle on my machine, do you have only java 8 installed? @AndreaClement
> 
> Strange, Android Studio only sees Java 8. I will correct that.

Not necessarily, it works in Android Studio (with Java 8 specified in Project Structure) but not in the terminal. I saw that the error occurs because I have Java 12 and should have 8. So I wanted to know which version do you have installed on your computer.

**Comment by SoupeDeKiwis** [comment]
@samuelchassot it looks like Android does not use higher than Java 8 (which we use on master). Do you wish to use 7 ?
(I personally have 8,11 and 13)

**Comment by samuelchassot** [comment]
> @samuelchassot it looks like Android does not use higher than Java 8 (which we use on master). Do you wish to use 7 ?

No, I'll install 8 for your project. But I don't understand why I could run tests for your colleagues project 2 days ago with java 12. Maybe some dependences that you use.
I'll come back when I would have been able to build your project to see the jacoco report.

**Comment by samuelchassot** [comment]
Okay I managed to run it locally. 
When the tests pass, the coverage I find in the report (locally) seems ok (around 71%). But you seem to have problem in your tests with the permissions (e.g. taking pictures). On the emulator, the pop up asking comes up and the test fails. As you run the tests always on the same device, you must have accepted them earlier but on a fresh one, there is a problem (so on travis it won't work great). 
I don't know how the coverage will be on code climate, but IMO you should tackle these problems and try again. I'll come back if problem occurs once more.

**Comment by SoupeDeKiwis** [comment]
Thanks for the help.
I take note that I could check the coverage locally ^^
I also observe that locally you face problems I did not encounter. Could you please tell me the smartphone you emulate ?

**Comment by samuelchassot** [comment]
> Thanks for the help.
> 
> I take note that I could check the coverage locally ^^
> 
> I also observe that locally you face problems I did not encounter. Could you please tell me the smartphone you emulate ?

Yep, I will give your more details tomorrow if you need but it is the Pixel 3 XL if I remember correctly. I'll run everything again and tomorrow and send you the log.

**Comment by samuelchassot** [comment]
So as promised, here are some details:
- I use the Pixel 3 XL API 29 emulator
- here is the output when I execute your tests: 

```
samuel@PixelDroid :branch camera > ./gradlew build connectedCheck jacocoTestReport
./gradlew: line 23: cd: "./: No such file or directory

> Task :app:kaptDebugKotlin
w: /Users/samuel/EPFL/SDP/PixelDroid/app/build/tmp/kapt3/stubs/debug/com/h/pixeldroid/db/AppDatabase.java:8: warning: Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.
public abstract class AppDatabase extends androidx.room.RoomDatabase {
                ^
w: [kapt] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: androidx.room.RoomProcessor (DYNAMIC).

> Task :app:compileDebugKotlin
w: /Users/samuel/EPFL/SDP/PixelDroid/app/src/main/java/com/h/pixeldroid/LoginActivity.kt: (163, 42): Parameter 'domain' is never used
w: /Users/samuel/EPFL/SDP/PixelDroid/app/src/main/java/com/h/pixeldroid/db/AppDatabase.kt: (25, 46): Variable 'instance' initializer is redundant

> Task :app:lint
Ran lint on variant release: 65 issues found
Ran lint on variant debug: 65 issues found
Wrote HTML report to file:///Users/samuel/EPFL/SDP/PixelDroid/app/build/reports/lint-results.html
Wrote XML report to file:///Users/samuel/EPFL/SDP/PixelDroid/app/build/reports/lint-results.xml

> Task :app:connectedDebugAndroidTest
Starting 13 tests on Pixel_3_XL_API_29(AVD) - 10

com.h.pixeldroid.MyProfileTest > testFollowersTextView[Pixel_3_XL_API_29(AVD) - 10] FAILED 
        androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
        at dalvik.system.VMStack.getThreadStackTrace(Native Method)

com.h.pixeldroid.SwipeTest > swipingRightOnHomepageShowsSettings[Pixel_3_XL_API_29(AVD) - 10] FAILED 
        androidx.test.espresso.NoActivityResumedException: No activities in stage RESUMED. Did you forget to launch the activity. (test.getActivity() or similar)?
        at dalvik.system.VMStack.getThreadStackTrace(Native Method)

> Task :app:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///Users/samuel/EPFL/SDP/PixelDroid/app/build/reports/androidTests/connected/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 48s
94 actionable tasks: 6 executed, 88 up-to-date

```
- I attached a screenshot of the authorization popup just in case
Capture d’écran 2020-03-18 à 10 38 46

**Comment by SoupeDeKiwis** [comment]
Thanks for log'.
I like how this is so inconsistent, between your results, Travis and my setup.

**Comment by SoupeDeKiwis** [comment]
Le code ayant drastiquement changé sur la branche photo, une PR sera fait depuis celle-ci.

**Pull request closed without merging**
