### PR TITLE
Upload picture implemented

### PR DESCRIPTION
**Pull request by ulysse42**
new fragment in the camera tab: added a button to upload a picture from local storage.
for now, it simply displays the said picture on the same fragment.
still need to link it with create a post and DB

### CODE REVIEW

**Comment by ulysse42** [comment]
- [ ] write tests

- [ ] save the picture to the app storage

- [ ] link it to post creation (todo next week)

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
> new fragment in the camera tab: added a button to upload a picture from local storage.

Doesn't #47 use that tab as well? You might want to coordinate with @samuelchassot

**Comment by ulysse42** [comment]
> Doesn't #47 use that tab as well? You might want to coordinate with @samuelchassot

with @AndreaClement indeed

**Comment by Wv5twkFEKh54vo4tta9yu7dHa3** [comment]
> > Doesn't #47 use that tab as well? You might want to coordinate with @samuelchassot
> 
> with @AndreaClement indeed

:laughing: damn it

**Review by SoupeDeKiwis — APPROVED** [review]

**Review by mjaillot — APPROVED** [review]

**Pull request merged**
